/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include "s21_string.h"
#include <string.h>
#include <stdlib.h>

const char a[] = "Hello world";
const char b[] = "Hello world\n\0";
const char c[] = "a\n\0";
const char d[] = " \n\0";
const char e[] = " \0";
const char f[] = "\n\0";
const char g[] = "\0";

START_TEST(test_s21_memchr)
{
ck_assert_ptr_eq(memchr(a, 'e', 4), s21_memchr(a, 'e', 4));
ck_assert_ptr_eq(memchr(a, 'd', 4), s21_memchr(a, 'd', 4));
ck_assert_ptr_eq(memchr(e, 'd', 1), s21_memchr(e, 'd', 1));
char *s1 = "This is a s21_memchr test";
ck_assert_ptr_eq(s21_memchr(s1, 's', 0), memchr(s1, 's', 0));
ck_assert_ptr_eq(s21_memchr(s1, 's', 2), memchr(s1, 's', 2));
ck_assert_ptr_eq(s21_memchr(s1, 's', 20), memchr(s1, 's', 20));
ck_assert_ptr_eq(s21_memchr(s1, 'u', 20), memchr(s1, 'u', 20));
ck_assert_ptr_eq(s21_memchr(s1, 'u', 25), memchr(s1, 'u', 25));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_s21_memchr);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
